### ISSUE TITLE
Frosted on WinXP (Python 2.7)

### ISSUE THREAD

**Issue by OscarL** [timothycrosley/deprecated.frosted#12]
I've installed frosted via: "pip install frosted". It downloaded/installed all the dependencies and frosted itself without a hiccup.

Trying to call "frosted" from a cmd.exe console says it cannot find such file/executable.

I go to C:\Python27\Scripts, and see a "frosted" file, but with no ".py" extension (pep8 installation, OTOH, l leaves there: "pep8.exe" and "pep8-script.py").

I add that .py extension, just to see if it works, and I get the following:

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\frosted.py", line 10, in <module>
    from frosted import __version__, settings
  File "C:\Python27\Scripts\frosted.py", line 10, in <module>
    from frosted import __version__, settings
ImportError: cannot import name __version__
```

"C:\Python27\Scripts\" is in the system path, so it seems "C:\Python27\Scripts\frosted.py" is trying to import the frosted module, but imports the script (that's why the rest of the packages create "package_name-script.py" files there).

Renaming C:\Python27\Scripts\frosted.py to C:\Python27\Scripts\frosted-script.py allows us to execute it from the command line.

You may want to check how other packages do the installation on Windows (I've never created one, so I'm of no help here).

**Comment by timothycrosley** [comment]
Thanks for reporting! Will release a new version soon to resolve this.

**Comment by timothycrosley** [comment]
Fixed in version 1.2.0, thanks again for reporting!

**Comment by OscarL** [comment]
Just checked it, now works like a charm. Thanks for your work!

**Comment by timothycrosley** [comment]
Glad to hear! Couldn't have done it without such a detailed bug report :)
