### ISSUE TITLE
Settings should not be read on import

### ISSUE THREAD

**Issue by rkern** [timothycrosley/deprecated.frosted#13]
`frosted.settings` does all of its work whenever it gets imported. This is fine for a command-line script, but it makes integrating `frosted` into a Python IDE impossible except by running the command-line script as a subprocess.

**Comment by timothycrosley** [comment]
Thanks for reporting! I agree this is not ideal, Will release a new version soon to resolve this.

**Comment by timothycrosley** [comment]
Thanks again for the suggestion, implemented dynamic settings in release 1.2.0
