### ISSUE TITLE
Is it possible to skip files with directory name?

### ISSUE THREAD

**Issue by ivanvolti** [timothycrosley/deprecated.frosted#25]
It would be great to skip files with a directory name as in .gitignore

```
[settings]
skip=migrations
```

I do:

```
frosted project/apps/**/*.py
```

I get a lot of migration files checked (project/apps/payments/migrations/0017_.py)
How can I ignore them?

This way is also could be intuitive:

```
frosted project/apps/**/*.py --skip migrations/*.py
```

**Comment by timothycrosley** [comment]
I agree, this would be a great feature. Will add it in before the next release.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
Support for skipping entire directories has been added to in version 1.2.1. Thanks again for suggesting this improvement!

~Timothy
