### ISSUE TITLE
Is there any way to ignore WARNING messages about skipped files?

### ISSUE THREAD

**Issue by ivanvolti** [timothycrosley/deprecated.frosted#28]
I get too many messages like "WARNING: project/migrations/0017.py was skipped as it's listed in 'skip' setting.

It makes it hard too have fast review of the result when I get so many messages I'm not interested in.

It could be great if user could see it only in verbose mode.

**Comment by timothycrosley** [comment]
I agree, will update it for the next release to only show WARNING messages about skipped files in verbose mode - or if only one file is supplied and it must be skipped.

Thanks!

Timothy

**Comment by aelgru** [comment]
:+1:

This would make it easier to create a PlugIn for [PyBuilder](https://github.com/pybuilder/pybuilder).

**Comment by timothycrosley** [comment]
Fixed in release 1.3.0, thanks again for pointing this out!

~Timothy
