### ISSUE TITLE
Verbose flag is not honoured for syntax errors

### ISSUE THREAD

**Issue by lcd047** [timothycrosley/deprecated.frosted#30]
The verbose flag is nice, it makes frosted's output parseable by other programs.  However, this flag is only honoured if the input file is syntactically valid.  Syntax errors are shown the non-verbose way.  It would be nice if the output format would be consistent regardless of input.  Perhaps a special error code could indicate syntax errors.

**Comment by timothycrosley** [comment]
Glad you cached this, I think your idea about a special syntax error is the right approach. Will fix before next release. 

Thanks!

Timothy

**Comment by timothycrosley** [comment]
Fixed in release 1.3.0, thanks again for pointing me to this design inconsistency!

~Timothy

**Comment by lcd047** [comment]
Thank you for the quick response.
