### ISSUE TITLE
wrong PythonSyntaxError keyword

### ISSUE THREAD

**Issue by Shura1oplot** [timothycrosley/deprecated.frosted#38]
Keyword indicates what word in the line of source code should be highlighted.
PythonSyntaxError has constant keyword 'syntax'. This keyword has no relation with the line of source code.
I think PythonSyntaxError keyword should be empty string.

**Comment by timothycrosley** [comment]
Thanks for pointing this out! I've released version 1.3.2 to address this issue, and I've added you to the contributor file.

~Timothy
