### ISSUE TITLE
__init__.py unused imports aren't actually skipped

### ISSUE THREAD

**Issue by monsanto** [timothycrosley/deprecated.frosted#49]
python 3.4, frosted 1.4.0

```
root@smogon-dev:/smogon/scms# frosted -r __init__.py
__init__.py:2: SCMSRepo imported but unused
```

contents of that file:

```
from .lib import SCMSRepo
```

**Comment by timothycrosley** [comment]
Hi @monsanto,

I think you mean to use the -s option (for skip):
    `frosted -r -s __init__.py`  .

should skip `__init__.py` while -r makes it run recursively and . is the run directory.

Thanks!

Tim
