### ISSUE TITLE
say what error code each error is

### ISSUE THREAD

**Issue by monsanto** [timothycrosley/deprecated.frosted#50]
right now, you get an error message like

```
./query.py:2: subqueryload imported but unused
```

if that's not actually an error, I need to consult this github page to find the error code to ignore. Would be helpful if the error message said the error code so I don't have to do that.

That being said this may be unnecessary when #46 is added

**Comment by lithammer** [comment]
You can run frosted with the `-vb` / `--verbose` flag to show error codes.

**Comment by timothycrosley** [comment]
Hi @monsanto,

Thanks for reporting this concern! However, @renstrom is correct, and this the desired behavior.

Thanks!

Tim
